name: wpsandbox
recipe: wordpress
config:
  php: '7.1'
  via: apache # or nginx
  database: mysql:5.6
  conf:
    php: php.ini
services:
  mailhog:
    # Spin up a mailhog container called "mailhog".
    type: mailhog
    # Hog from appserver or nginx as appropriate.
    hogfrom:
      - appserver
proxy:
  appserver:
    - wpsandbox.test
